# Generated by Django 4.0.1 on 2022-01-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_relations',
            old_name='product_image',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='product_relations',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='product_relations',
            name='product_size',
        ),
    ]
